### PR TITLE
Home page added. Initial filters. Preparation for map. Refactoring.

### PR DESCRIPTION
**Pull request by GroxExMachine**

### CODE REVIEW

**Comment by GroxExMachine** [comment]
Unable to get results from Zeit.co now. On Windows and Linux in appropriate time.

**Comment by GroxExMachine** [comment]
https://build-ylovfsboem.now.sh/

**Comment by evgenyrodionov** [comment]
https://github.com/GroxExMachine/airbnb-demo-frontend/pull/1#issuecomment-345647406

**Comment by GroxExMachine** [comment]
Done.

**Pull request closed without merging**
